name = "c"
title = "C Driver"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

# toc_landing_pages = ["/paths/to/pages/that/have/nested/content"]

[constants]

version = "1.26"
full-version = "{+version+}.1"
range-is-experimental = "Range algorithm is experimental only and not intended for public use. It is subject to breaking changes."
api-is-experimental = "This API is part of the experimental Queryable Encryption PI and may be subject to breaking changes in future releases."