name = "c"
title = "C Driver"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv",
                "https://www.mongodb.com/docs/drivers/objects.inv",
              ]

toc_landing_pages = [
    "/libbson",
    "/libbson/tutorials",
    "/libbson/guides",
    "/libbson/cross-platform-notes",
    "/libbson/api",
    "/libbson/api/bson_context_t",
    "/libbson/api/bson_decimal128_t",
    "/libbson/api/bson_error_t",
    "/libbson/api/bson_iter_t",
    "/libbson/api/bson_json_reader_t",
    "/libbson/api/bson_memory",
    "/libbson/api/bson_oid_t",
    "/libbson/api/bson_reader_t",
    "/libbson/api/bson_string_t",
    "/libbson/api/bson_t",
    "/libbson/api/bson_value_t",
    "/libbson/api/bson_writer_t",
    "/libbson/api/character_string_routines",
    "/libbson/api/version",
    "/libbson/tutorial",
    "/libmongoc",
    "/libmongoc/api",
    "/libmongoc/api/errors",
    "/libmongoc/api/init-cleanup",
    "/libmongoc/api/mongoc_auto_encryption_opts_t",
    "/libmongoc/api/mongoc_bulk_operation_t",
    "/libmongoc/api/mongoc_change_stream_t",
    "/libmongoc/api/mongoc_client_encryption_t",
    "/libmongoc/api/mongoc_client_pool_t",
    "/libmongoc/api/mongoc_client_session_t",
    "/libmongoc/api/mongoc_client_t",
    "/libmongoc/api/mongoc_collection_t",
    "/libmongoc/api/mongoc_cursor_t",
    "/libmongoc/api/mongoc_database_t",
    "/libmongoc/api/mongoc_find_and_modify_opts_t",
    "/libmongoc/api/mongoc_gridfs_t",
    "/libmongoc/api/mongoc_index_opt_t",
    "/libmongoc/api/mongoc_optional_t",
    "/libmongoc/api/mongoc_rand",
    "/libmongoc/api/mongoc_read_concern_t",
    "/libmongoc/api/mongoc_read_prefs_t",
    "/libmongoc/api/mongoc_server_api_t",
    "/libmongoc/api/mongoc_server_description_t",
    "/libmongoc/api/mongoc_session_opt_t",
    "/libmongoc/api/mongoc_socket_t",
    "/libmongoc/api/mongoc_stream_t",
    "/libmongoc/api/mongoc_topology_description_t",
    "/libmongoc/api/mongoc_transaction_opt_t",
    "/libmongoc/api/mongoc_uri_t",
    "/libmongoc/api/mongoc_version",
    "/libmongoc/api/mongoc_write_concern_t",
    "/libmongoc/application-performance-monitoring",
    "/libmongoc/guides",
    "/libmongoc/howto",
    "/libmongoc/ref",
    "/libmongoc/tutorials",
    "/libmongoc/tutorials/obtaining-libraries",
]
sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

[constants]

version = "1.26"
full-version = "{+version+}.2"
is-experimental = "is part of the experimental Queryable Encryption API and may be subject to breaking changes in future releases."
range-is-experimental = "Range algorithm is experimental only and not intended for public use. It is subject to breaking changes."
api-is-experimental = "This API {+is-experimental+}"
opt-is-experimental = "This option {+is-experimental+}"