name = "c"
title = "C Driver"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

toc_landing_pages = [
    "/source/docs-libmongoc/api",
    "/source/docs-libmongoc/api/errors",
    "/source/docs-libmongoc/api/init-cleanup",
    "/source/docs-libmongoc/api/mongoc_auto_encryption_opts_t",
    "/source/docs-libmongoc/api/mongoc_bulk_operation_t",
    "/source/docs-libmongoc/api/mongoc_change_stream_t",
    "/source/docs-libmongoc/api/mongoc_client_encryption_t",
    "/source/docs-libmongoc/application-performance-monitoring",
    "/source/docs-libmongoc/guides",
    "/source/docs-libmongoc/howto",
    "/source/docs-libmongoc/includes",
    "/source/docs-libmongoc/ref",
    "/source/docs-libmongoc/static",
    "/source/docs-libmongoc/tutorials",
]

[constants]

version = "1.26"
full-version = "{+version+}.1"
range-is-experimental = "Range algorithm is experimental only and not intended for public use. It is subject to breaking changes."
api-is-experimental = "This API is part of the experimental Queryable Encryption PI and may be subject to breaking changes in future releases."